#!/bin/bash
pip install jupyterlab==2.2.0
pip install matplotlib==3.2.0
pip install yt==3.6.0
pip install voila==0.1.21
pip install pandas==1.1.0
pip install h5py==2.10.0
pip install jupyterlab_launcher>=0.5.0
pip install bqplot==0.12.15
pip install numpy==1.19.1
pip install ipyvuetify==1.5.0
pip install pythreejs==2.2.0
conda update -n base conda
conda env update -f voila.yml
jupyter labextension install @jupyter-voila/jupyterlab-preview
jupyter serverextension enable voila --sys-prefix
git clone https://github.com/data-exp-lab/widgyts.git
cd widgyts
git init
git remote add upstream https://github.com/data-exp-lab/widgyts.git
git pull upstream grid_view_widget
pip install -e .