#!/bin/bash
# have to re-do this since the requirements.txt did not work for 
# pkg matplotlib. Guess the problem might be Jupyter Lab
pip install -r binder/requirements.txt 
jupyter labextension install @jupyter-voila/jupyterlab-preview
jupyter serverextension enable voila --sys-prefix
# install the PR from Wigyts
git clone https://github.com/data-exp-lab/widgyts.git
cd widgyts
git init
git remote add upstream https://github.com/data-exp-lab/widgyts.git
git pull upstream grid_view_widget
pip install -e .
